version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - "./:/app"
    links:
      - mongodb
      - redis
    depends_on:
      - redis
      - mongodb
  mongodb:
    image: mongo:3.4
    volumes:
      - mongodata:/data/db/mongo
    ports:
      - "27017:27017"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  redis:
    image: redis
    volumes:
      - redisdata:/data/db/redis
    ports:
      - "6379:6379"
volumes:
  mongodata:
  redisdata:

